library(shiny)
library(bs4Dash)
library(dplyr)
library(readxl)
library(ggplot2)
library(leaflet)
library(sf)
library(plotly)
library(DT)
library(rsconnect)
library(rnaturalearthdata)
#Chargement des données 
#rsconnect::deployApp()
donnees <- read_excel("data_in/opale_2024.xlsx")
donnees_2025 <- read_excel("data_in/opale_2025.xlsx")
embrun_marker <- readRDS("data_in/embrun.RDS")
embrun_marker_2025 <- readRDS("data_in/embrun_2025.RDS")
centroides_data <- readRDS("data_in/centroides.RDS")
centroides_data_2025 <- readRDS("data_in/centroides_data_2025.RDS")
